Repository Feminine-Divine/periodo, pull requests merged in 2021-05, with the labels that each got.

#252 setup prettier and eslint
  periodo/.eslintignore
  periodo/.eslintrc.json
  periodo/.prettierignore
  periodo/.prettierrc
  periodo/components/ChatBot/ChatBot.js
  periodo/components/ChatBot/chatBot.module.css
  periodo/components/Emergency/Emergency.js
  periodo/components/Emergency/emergency.module.css
  periodo/components/Footer/ContactUs.js
  periodo/components/Footer/Footer.js
  periodo/components/Footer/Footer.module.css
  periodo/components/Gynae/Gynac.js
  periodo/components/Gynae/Gynac.module.css
  periodo/components/Gynae/Userform.js
  periodo/components/about/about.js
  periodo/components/about/aboutstyle.js
  periodo/components/about/aboutstyle.module.css
  periodo/components/analysis/Analysis.js
  periodo/components/analysis/Analysis.module.css
  periodo/components/calender/calender.js
  periodo/components/calender/calender.module.css
  periodo/components/dialogbox/DialogNextButton.js
  periodo/components/flow/Flow.js
  periodo/components/flow/Flow.module.css
  periodo/components/navbar.css
  periodo/components/navbar.js
  periodo/components/navbar.module.css
  periodo/components/notes/CreateArea.js
  periodo/components/notes/Notes.module.css
  periodo/components/notes/ShowNotes.js
  periodo/components/started.js
  periodo/components/started.module.css
  periodo/components/styles.js
  periodo/docker-compose.yml
  periodo/next.config.js
  periodo/package-lock.json
  periodo/package.json
  periodo/pages/Gynac.js
  periodo/pages/LoginPage.js
  periodo/pages/Review.js
  periodo/pages/SignUp.js
  periodo/pages/SimpleForm.js
  periodo/pages/_app.js
  periodo/pages/_document.js
  periodo/pages/about.js
  periodo/pages/analysis.js
  periodo/pages/api/auth/callback.js
  periodo/pages/api/auth/login.js
  periodo/pages/api/auth/logout.js
  periodo/pages/api/auth/me.js
  periodo/pages/api/auth/profile.js
  periodo/pages/calender.js
  periodo/pages/flow.js
  periodo/pages/homepage.js
  periodo/pages/notes.js
  periodo/pages/tips.js
  periodo/styles/globals.css
  periodo/tsconfig.json
  periodo/utils/auth0.js
Labels: Level3, gssoc21

#267 Added floating animation to svg in about us section.
  package-lock.json
  periodo/components/about/aboutstyle.js
  periodo/components/about/aboutstyle.module.css
  periodo/package-lock.json
Labels: Level2, gssoc21

#266 Placed content to bottom in footer
  periodo/components/Footer/Footer.module.css
Labels: Level2, gssoc21

#257 Created Common layout
  periodo/components/Layout.js
  periodo/components/about/about.js
  periodo/components/tips/tips.js
  periodo/pages/Gynac.js
  periodo/pages/about.js
  periodo/pages/analysis.js
  periodo/pages/calender.js
  periodo/pages/flow.js
  periodo/pages/homepage.js
  periodo/pages/notes.js
  periodo/pages/tips.js
Labels: Level3, gssoc21

#269 Issue-268
  .github/CONTRIBUTING.md
Labels: Level1, gssoc21

#272 Created User Profile Page
  periodo/components/navbar.css
  periodo/components/navbar.js
  periodo/components/profile/imageupload.js
  periodo/components/profile/profile.js
  periodo/components/profile/profile.module.css
  periodo/components/profile/upload.module.css
  periodo/package-lock.json
  periodo/pages/profile.js
  periodo/public/background.jpg
  periodo/public/img_upload.png
  periodo/public/placeholder_icon.png
  periodo/yarn.lock
Labels: Level3, gssoc21

#270 Set up responsive buttons in calnder and changed color of weeks
  periodo/components/calender/calender.js
  periodo/components/calender/calender.module.css
Labels: Level2, gssoc21

#286 navigation drawer added
  periodo/components/navbar.component.style.js
  periodo/components/navbar.css
  periodo/components/navbar.js
  periodo/components/started.module.css
Labels: Level3, gssoc21

#294 change color and fixed issue of appbar
  periodo/components/about/aboutstyle.module.css
  periodo/components/calender/calender.module.css
  periodo/components/navbar.js
  periodo/components/notes/Notes.module.css
  periodo/components/tips/cards.module.css
Labels: Level2, gssoc21

#293 move secret keys to .env file
  periodo/.env
  periodo/utils/auth0.js
Labels: Level1, gssoc21

#290 Fixes:Clean the code #282
  periodo/components/ChatBot/ChatBot.js
  periodo/components/ChatBot/chatBot.module.css
  periodo/components/Emergency/Emergency.js
  periodo/components/Emergency/emergency.module.css
  periodo/components/Footer/ContactUs.js
  periodo/components/Footer/Footer.module.css
  periodo/components/Gynae/Gynac.js
  periodo/components/Gynae/Gynac.module.css
  periodo/components/Gynae/Userform.js
  periodo/components/about/about.js
  periodo/components/about/aboutstyle.js
  periodo/components/about/aboutstyle.module.css
  periodo/components/analysis/Analysis.js
  periodo/components/analysis/Analysis.module.css
  periodo/components/calender/calender.js
  periodo/components/calender/calender.module.css
  periodo/components/dialogbox/DialogNextButton.js
  periodo/components/flow/Flow.js
  periodo/components/flow/Flow.module.css
  periodo/components/navbar.css
  periodo/components/navbar.js
  periodo/components/notes/Notes.js
  periodo/components/notes/Notes.module.css
  periodo/components/notes/ShowNotes.js
  periodo/components/profile/imageupload.js
  periodo/components/profile/profile.js
  periodo/components/profile/profile.module.css
  periodo/components/profile/upload.module.css
  periodo/components/splashScreen/SplashScreen.js
  periodo/components/splashScreen/SplashScreen.module.css
  periodo/components/started.js
  periodo/components/started.module.css
  periodo/components/tips/card.js
  periodo/components/tips/cards.module.css
  periodo/styles/Home.module.css
Labels: Level3, gssoc21

#298 Aligned the items properly for mobile view of about us section
  periodo/components/about/aboutstyle.module.css
Labels: Level2, gssoc21

#306 Fixed Responsiveness of Calendar UI
  periodo/components/calender/calender.module.css
Labels: Level2, gssoc21

#314 Added dynamic year feature
  periodo/components/Footer/Footer.js
Labels: Level2, gssoc21

#307 navbar
  periodo/components/navbar.css
  periodo/components/navbar.js
Labels: Level2, gssoc21

#316 Improved fonts of about us page
  periodo/components/about/aboutstyle.module.css
Labels: Level2, gssoc21

#322 implement dark mode
  periodo/components/Footer/ContactUs.js
  periodo/components/Footer/Footer.module.css
  periodo/package.json
  periodo/public/homepage.js
Labels: Level3, gssoc21

#296 Fixes:UI improvement Talk to us form
  node_modules/font-awesome/.npmignore
  node_modules/font-awesome/HELP-US-OUT.txt
  node_modules/font-awesome/README.md
  node_modules/font-awesome/css/font-awesome.css
  node_modules/font-awesome/css/font-awesome.css.map
  node_modules/font-awesome/css/font-awesome.min.css
  node_modules/font-awesome/fonts/FontAwesome.otf
  node_modules/font-awesome/fonts/fontawesome-webfont.eot
  node_modules/font-awesome/fonts/fontawesome-webfont.svg
  node_modules/font-awesome/fonts/fontawesome-webfont.ttf
  node_modules/font-awesome/fonts/fontawesome-webfont.woff
  node_modules/font-awesome/fonts/fontawesome-webfont.woff2
  node_modules/font-awesome/less/animated.less
  node_modules/font-awesome/less/bordered-pulled.less
  node_modules/font-awesome/less/core.less
  node_modules/font-awesome/less/fixed-width.less
  node_modules/font-awesome/less/font-awesome.less
  node_modules/font-awesome/less/icons.less
  node_modules/font-awesome/less/larger.less
  node_modules/font-awesome/less/list.less
  node_modules/font-awesome/less/mixins.less
  node_modules/font-awesome/less/path.less
  node_modules/font-awesome/less/rotated-flipped.less
  node_modules/font-awesome/less/screen-reader.less
  node_modules/font-awesome/less/stacked.less
  node_modules/font-awesome/less/variables.less
  node_modules/font-awesome/package.json
  node_modules/font-awesome/scss/_animated.scss
  node_modules/font-awesome/scss/_bordered-pulled.scss
  node_modules/font-awesome/scss/_core.scss
  node_modules/font-awesome/scss/_fixed-width.scss
  node_modules/font-awesome/scss/_icons.scss
  node_modules/font-awesome/scss/_larger.scss
  node_modules/font-awesome/scss/_list.scss
  node_modules/font-awesome/scss/_mixins.scss
  node_modules/font-awesome/scss/_path.scss
  node_modules/font-awesome/scss/_rotated-flipped.scss
  node_modules/font-awesome/scss/_screen-reader.scss
  node_modules/font-awesome/scss/_stacked.scss
  node_modules/font-awesome/scss/_variables.scss
  node_modules/font-awesome/scss/font-awesome.scss
  package-lock.json
  periodo/components/Footer/ContactUs.js
  periodo/components/Footer/ContactUs.module.css
  periodo/components/Footer/Footer.js
  periodo/components/Footer/Footer.module.css
  periodo/components/Layout.js
Labels: Level3, gssoc21

#301 Fixed bug to make Analysis page responsive
  periodo/components/analysis/Analysis.js
  periodo/components/analysis/Analysis.module.css
Labels: Level2, gssoc21

#336 integrate google maps using react
  periodo/components/Footer/Footer.module.css
  periodo/components/Gynae/GoogleMap.js
  periodo/components/Gynae/Gynac.js
  periodo/package-lock.json
  periodo/package.json
  periodo/yarn.lock
Labels: Level3, gssoc21

#345 calander page
  periodo/components/calender/calender.js
  periodo/components/calender/calender.module.css
Labels: Level2, gssoc21

#347 scrolltop
  periodo/components/Footer/Footer.js
  periodo/components/Footer/scrolltop.js
  periodo/components/Footer/scrolltop.module.css
  periodo/components/Layout.js
  periodo/package-lock.json
  periodo/package.json
  periodo/pages/_app.js
  periodo/pages/homepage.js
  periodo/styles/globals.css
Labels: Level2, gssoc21

#346 Quiz responsive
  periodo/components/Footer/ContactUs.module.css
  periodo/components/about/aboutstyle.js
  periodo/components/about/aboutstyle.module.css
  periodo/components/analysis/Analysis.js
  periodo/components/analysis/Analysis.module.css
Labels: Level2, gssoc21

#351 Fixed chatboat and restroom button in -#319
  periodo/components/ChatBot/chatBot.module.css
  periodo/components/Footer/Footer.module.css
Labels: Level2, gssoc21

#360 Hover style to logo in Footer
  periodo/components/Footer/Footer.module.css
Labels: Level2, gssoc21

#335 Added Speech Feature To ChatBot.
  periodo/pages/SimpleForm.js
Labels: Level3, gssoc21

#372 Create Welcome-Bot
  .github/workflows/greetings.yml
Labels: Level2, gssoc21

#374 resolved gynac page
  periodo/components/Gynae/Gynac.js
Labels: Level2, gssoc21

#367 Fixed Contact Form Responsiveness
  periodo/components/Footer/ContactUs.module.css
Labels: Level2, gssoc21

#378 Social campaign
  periodo/components/navbar.js
  periodo/components/social/social.js
  periodo/components/social/social.module.css
  periodo/pages/social.js
  periodo/yarn.lock
Labels: Level3, gssoc21

#377 prior or delay period graphs
  periodo/components/flow/Flow.js
Labels: Level3, gssoc21

#373 FAQs in navbar
  periodo/components/FAQs/questions.js
  periodo/components/FAQs/questions.module.css
  periodo/components/navbar.js
  periodo/package-lock.json
  periodo/pages/questions.js
Labels: Level3, gssoc21

#382 Fixed Responsiveness of Social Campaign Page
  periodo/components/social/social.js
  periodo/components/social/social.module.css
Labels: Level2, gssoc21

#384 Updated readme
  README.md
Labels: Level1, gssoc21

#386 bugs in quiz page
  periodo/components/analysis/Analysis.js
  periodo/components/analysis/Analysis.module.css
Labels: Level2, gssoc21

#394 Flowpage responsive
  periodo/components/Footer/ContactUs.module.css
  periodo/components/flow/Flow.js
Labels: Level2, gssoc21

#398 gynac help
  periodo/components/Gynae/Gynac.js
  periodo/components/Gynae/Gynac.module.css
Labels: Level2, gssoc21

#402 Added Logo of Social Campaign
  periodo/components/navbar.js
Labels: Level2, gssoc21

#403 faqs page responsive
  periodo/components/FAQs/questions.module.css
Labels: Level2, gssoc21
