Repository Feminine-Divine/periodo, pull requests merged in 2021-04, with the labels that each got.

#160 Update README.md
  README.md
Labels: Level 0, gssoc21

#157 added link to homepage to logo on navbar
  periodo/components/navbar.js
  periodo/yarn.lock
Labels: Level 2, gssoc21

#176 Improved UI of input field in notes page
  periodo/components/notes/CreateArea.js
  periodo/components/notes/Notes.module.css
Labels: Level 2, gssoc21

#180 Custom Scrollbar added
  periodo/styles/globals.css
Labels: Level 2, gssoc21

#169 link to flow in navbar.
  periodo/components/navbar.js
Labels: Level2, gssoc21

#163 hover effect added to About
  periodo/components/about/aboutstyle.js
  periodo/components/about/aboutstyle.module.css
  periodo/package-lock.json
  periodo/yarn.lock
Labels: Level2, gssoc21

#198 Gynac UI
  periodo/components/Gynae/Gynac.js
  periodo/components/Gynae/Gynac.module.css
Labels: Level2, gssoc21

#207 modify the do you wanna share exp prompt
  periodo/components/calender/calender.module.css
  periodo/components/dialogbox/DialogNextButton.js
  periodo/yarn.lock
Labels: Level2, gssoc21

#208 Opaque background. #148
  periodo/components/Gynae/Gynac.js
  periodo/components/Gynae/Gynac.module.css
  periodo/styles/globals.css
Labels: Level2, gssoc21

#206 Card: thumbnail images
  periodo/components/tips/bgg.png
  periodo/components/tips/card.js
  periodo/components/tips/cards.module.css
  periodo/components/tips/tips.js
  periodo/pages/tips.js
Labels: Level2, gssoc21

#221 Update README.md
  README.md
Labels: Level0, gssoc21

#210 Prescriptions/Advice based on Quiz response
  periodo/components/about/about.js
  periodo/components/about/aboutstyle.js
  periodo/components/about/aboutstyle.module.css
  periodo/components/analysis/Analysis.js
  periodo/components/analysis/Analysis.module.css
  periodo/components/navbar.js
  periodo/pages/SimpleForm.js
  periodo/public/Checklist.svg
  periodo/public/Congrats.svg
  periodo/public/Questions.svg
Labels: Level3, gssoc21

#218 Added responsivness to the website
  periodo/components/Footer/Footer.module.css
  periodo/components/calender/calender.js
  periodo/components/calender/calender.module.css
  periodo/components/started.js
  periodo/components/started.module.css
  periodo/styles/globals.css
Labels: Level3, gssoc21

#230 Footer Revamped!
  periodo/components/Footer/Footer.js
  periodo/components/Footer/Footer.module.css
Labels: Level3, gssoc21

#234 Mailid
  periodo/components/Footer/Footer.js
  periodo/components/Footer/Footer.module.css
Labels: Level2, gssoc21

#239 Add files via upload
  periodo/assets/Feminine Divine (1).png
Labels: Level3, gssoc21
