Repository Feminine-Divine/periodo, pull requests merged in 2021-03, with the labels that each got.

#18 Adding the demo project video link to the README
  README.md
Labels: GSSoC'21, Level 0

#15 Added-PR-template
  .github/PR_template.md
  .github/pull_request_template.md
Labels: GSSoC'21

#37 Buttons improved.
  periodo/components/started.module.css
  periodo/styles/globals.css
Labels: gssoc21

#41 Add navbar to the Flow page
  periodo/pages/flow.js
Labels: gssoc21

#35 Added a Tips Page
  periodo/components/flow/Flow.js
  periodo/components/navbar.js
  periodo/components/tips/card.js
  periodo/components/tips/cards.module.css
  periodo/components/tips/tips.js
  periodo/package-lock.json
  periodo/package.json
  periodo/pages/flow.js
  periodo/pages/tips.js
  periodo/yarn.lock
Labels: Level 3, gssoc21

#23 issue_templates added in .github
  periodo/.github/ISSUE_TEMPLATE/bug.md
  periodo/.github/ISSUE_TEMPLATE/documentation.md
  periodo/.github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc21

#60 Added the new logo in navbar
  periodo/components/navbar.js
  periodo/public/Logo.png
  periodo/yarn.lock
Labels: Level 3, gssoc21

#43 Added range feature in calendar
  periodo/components/calender/calender.js
  periodo/components/calender/calender.module.css
  periodo/package-lock.json
  periodo/package.json
Labels: Level 3, gssoc21

#53 Fix About Section fixes #45
  README.md
Labels: Level 0, gssoc21

#81 Link to calendar in navbar.
  periodo/components/navbar.js
Labels: Level 2, Ready to merge, gssoc21

#85 Display a dialogbox for confirmation
  README.md
  periodo/components/calender/calender.js
  periodo/components/dialogbox/DialogNextButton.js
  periodo/yarn.lock
Labels: Level 3, gssoc21

#70 Styled the rating labels
  periodo/components/flow/Flow.js
  periodo/components/flow/Flow.module.css
  periodo/package-lock.json
  periodo/package.json
Labels: Level 2, gssoc21

#98 Github badges added
  README.md
Labels: Level 0, gssoc21

#94 added styling in tips page
  periodo/components/tips/cards.module.css
Labels: Level 2, gssoc21

#99 Improvment in Navbar #87
  periodo/components/navbar.css
  periodo/components/navbar.js
  periodo/components/styles.js
  periodo/styles/globals.css
Labels: Level 2, Ready to merge, gssoc21

#56 Adding CSS animation effect to the title of homepage
  periodo/components/started.module.css
  periodo/package-lock.json
  periodo/yarn.lock
Labels: Level 2, gssoc21

#102 Create a splash screen
  periodo/components/splashScreen/SplashScreen.js
  periodo/components/splashScreen/SplashScreen.module.css
  periodo/pages/index.js
  periodo/public/woman_sitting.svg
  periodo/public/woman_v_sign.svg
  periodo/public/woman_walking.svg
  periodo/public/woman_with_chart.svg
  periodo/styles/globals.css
Labels: Level 3, gssoc21

#106 page for adding notes
  periodo/components/navbar.js
  periodo/components/notes/CreateArea.js
  periodo/components/notes/Notes.js
  periodo/components/notes/Notes.module.css
  periodo/components/notes/ShowNotes.js
  periodo/package-lock.json
  periodo/package.json
  periodo/pages/notes.js
  periodo/yarn.lock
Labels: Level 3, gssoc21

#105 about page addition
  periodo/components/about/about.js
  periodo/components/about/aboutstyle.js
  periodo/components/about/aboutstyle.module.css
  periodo/components/navbar.js
  periodo/pages/about.js
  periodo/public/Calendar.svg
  periodo/public/Chatbot.svg
  periodo/public/Diet.svg
  periodo/public/Medicine.svg
Labels: Level 3, gssoc21

#116 Updated Gynac Help changes
  periodo/components/Gynae/Gynac.js
  periodo/components/Gynae/Userform.js
  periodo/components/navbar.js
  periodo/pages/Gynac.js
Labels: Level 3, gssoc21

#119 112 Adjust navbar
  periodo/components/navbar.css
  periodo/components/navbar.js
  periodo/components/styles.js
Labels: Level 2, gssoc21

#107 Added loginPage
  periodo/pages/LoginPage.js
  periodo/pages/SignUp.js
Labels: gssoc21

#120 Fixed overlapping
  periodo/components/about/aboutstyle.module.css
Labels: Level 2, gssoc21

#47 Third-party authentication added using nextjs-auth0 Issue #16
  periodo/.env
  periodo/components/navbar.js
  periodo/package-lock.json
  periodo/package.json
  periodo/pages/api/auth/callback.js
  periodo/pages/api/auth/login.js
  periodo/pages/api/auth/logout.js
  periodo/pages/api/auth/me.js
  periodo/pages/api/auth/profile.js
  periodo/tsconfig.json
  periodo/utils/auth0.js
  periodo/yarn.lock
Labels: Level 3, gssoc21

#132 fixed submission of empty note
  periodo/components/notes/CreateArea.js
  periodo/components/notes/Notes.module.css
Labels: Level 3, gssoc21

#139 Added Hover Effects on Card & Read More
  periodo/components/tips/cards.module.css
Labels: Level 2, gssoc21

#151 Made website responsive
  periodo/components/Gynae/Gynac.js
  periodo/components/Gynae/Gynac.module.css
  periodo/components/about/about.js
  periodo/components/about/aboutstyle.js
  periodo/components/about/aboutstyle.module.css
  periodo/components/analysis/Analysis.module.css
  periodo/components/navbar.css
  periodo/components/navbar.js
  periodo/components/notes/Notes.module.css
  periodo/components/started.module.css
  periodo/components/tips/cards.module.css
  periodo/package-lock.json
  periodo/public/menu.svg
  periodo/public/x.svg
  periodo/styles/globals.css
Labels: Level 2, gssoc21

#147 Add ChatBot feature
  periodo/components/ChatBot/ChatBot.js
  periodo/package-lock.json
  periodo/package.json
  periodo/pages/Review.js
  periodo/pages/SimpleForm.js
  periodo/pages/homepage.js
  periodo/styles/globals.css
Labels: Level 3, gssoc21

#159 Added Styling to the ChatBot Button
  periodo/components/ChatBot/ChatBot.js
  periodo/components/ChatBot/chatBot.module.css
  periodo/package-lock.json
  periodo/styles/globals.css
Labels: Level 2, gssoc21
